services:
  postgres:
    image: docker.io/library/postgres:14-bullseye
    environment:
      - "POSTGRES_USER=hostsdottxt"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=hostsdottxt"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data/pgdata

volumes:
  postgres:
