#!/bin/sh

if [ ! -f /etc/hostsdottxt.env ]; then
	echo "DATABASE_URL=" >> /etc/hostsdottxt.env
	echo "JWT_SECRET=" >> /etc/hostsdottxt.env
fi

systemctl is-active --quiet hdt-api && systemctl restart hdt-api || true
